version: "3"
services:
  angular-clients:
    build: UI
    ports:
      - "4200:4200"
    networks:
      - mean-app

  express-client:
    build: API
    ports:
      - "3002:3002"
    depends_on:
      - database
    networks:
      - mean-app

  database:
    image: mongo
    command: mongod --port 27018
    ports:
      - "27018:27018"
    networks:
      - mean-app
    volumes:
      - mongo-data:/data/db

networks:
  mean-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
